services:
  - type: web
    name: soil-classifier-api
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URI
        sync: false   # We'll set this manually
      - key: PYTHON_VERSION
        value: 3.11.6
    autoDeploy: true
    disk:
      name: models
      mountPath: /opt/render/project/src/models
      sizeGB: 1